# Create a pod with a pvc and snapshot the pv using k8s volume snapshots CRD

# Shift to minikube and run
# minikube addons enable volumesnapshots
# minikube addons enable csi-hostpath-driver
# kubectl apply -f test-pvc.yaml
# kubectl apply -f nginx-with-pvc-pod.yaml
# kubectl apply -f volumesnapshotclass.yaml
# kubectl apply -f test-snapshot.yaml

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: ns-two
spec:
  containers:
  - name: test-container
    image: nginx:stable
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/mnt/test"
      name: test-volume
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: test-pvc
