apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: ns-two
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: csi-hostpath-sc
