# Create a secret from literal and from file to check if in which cases values are encoded and in which case they are not.

# File content is encoded, but literals are not encoded.

apiVersion: v1
kind: Secret
metadata:
  name: file
type: Opaque
stringData:
  config.yaml: |
    apiUrl: "https://my.api.com/api/v1"
    username: <user>
    password: <password>
