apiVersion: v1
kind: Pod
metadata:
  name: kanister-kubectl-pod
  namespace: default
spec:
  serviceAccountName: kanister-sa
  containers:
  - name: kanister-kubectl
    image: kanisterio/kanister-kubectl:1.18
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"] # Keep the pod running for an hour
