# Create a secret and set all the key value pairs of the secret as environment variable into a pod.

apiVersion: v1
kind: Pod
metadata:
  name: secret-usage
spec:
  containers:
    - name: my-container
      image: nginx  
      envFrom:
        - secretRef:
            name: passwords
