apiVersion: v1
kind: Pod
metadata:
  name: static-file-server
  labels:
    app: static-file-server
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
  initContainers:
  - name: init-static-file
    image: busybox
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" > /usr/share/nginx/html/index.html']
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-data
    emptyDir: {}