apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-listing-rolebinding
subjects:
- kind: ServiceAccount
  name: kanister-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-listing
  apiGroup: rbac.authorization.k8s.io
